theme = "tokyonight"

[editor]
completion-timeout = 5
mouse = true
auto-save = true
cursorline = true
bufferline = "always"

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.file-picker]
hidden = false

[editor.indent-guides]
render = true
character = "▏" # Some characters that work well: "▏", "┆", "┊", "⸽"
skip-levels = 1

[editor.lsp]
display-inlay-hints = true

[editor.soft-wrap]
enable = true
#wrap-at-text-width = true
wrap-indicator = "↩ "

[editor.statusline]
left = [ "mode", "spinner", "file-name", "read-only-indicator", "file-modification-indicator", "version-control", "diagnostics" ]
right = [ "selections", "register", "position", "position-percentage", "total-line-numbers", "file-encoding" ]
separator = "│"
mode.normal = "N"
mode.insert = "I"
mode.select = "S"

[keys.normal.space.g]
g = ":sh zellij run -fc --height 100% --width 100% --x 1 --y 1 -- lazygit"

