theme = "tokyonight"

[editor]
completion-timeout = 5
mouse = true
auto-save = true
cursorline = false
bufferline = "always"

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.file-picker]
hidden = false

[editor.indent-guides]
render = true
character = "▏" # Some characters that work well: "▏", "┆", "┊", "⸽"
skip-levels = 1

[editor.lsp]
display-inlay-hints = true

[editor.soft-wrap]
enable = true
#wrap-at-text-width = true
wrap-indicator = "↩ "

[editor.statusline]
left = [ "mode", "spinner", "file-name", "read-only-indicator", "file-modification-indicator", "version-control", "diagnostics" ]
right = [ "primary-selection-length", "register", "position", "position-percentage", "total-line-numbers", "file-encoding" ]
separator = "│"
mode.normal = "N"
mode.insert = "I"
mode.select = "S"

[keys.normal]
# C-e = "scroll_down"
# C-y = "scroll_up"
C-e = ["scroll_down", "move_line_down"]
C-y = ["scroll_up", "move_line_up"]
S-down = ["extend_to_line_bounds", "delete_selection", "paste_after"]
S-up = ["extend_to_line_bounds", "delete_selection", "move_line_up", "paste_before"]

[keys.normal.space.g]
g = ":sh zellij run -fc --height 100% --width 100% --x 1 --y 1 -- gitui"
#g = [":new", ":insert-output lazygit", ":buffer-close!", ":redraw"]
n = [":new", ":sh zellij run -f -x 10% -y 10% --width 80% --height 80% -- bash ~/.config/helix/yazi-picker.sh", ":buffer-close!", ":redraw"]

[keys.select]
S-down = ["delete_selection", "paste_after"]
S-up = ["delete_selection", "move_line_up", "paste_before"]

