[[language]]
name = "toml"
auto-format = true
formatter = { command = "prettier", args = ["--parser", "toml"] }

[[language]]
auto-format = true
name = "json"
formatter = { command = "prettier", args = ["--parser", "json"] }

[[language]]
name = "javascript"
auto-format = true

[[language]]
name = "typescript"
auto-format = true

[[language]]
name = "markdown"
# https://github.com/executablebooks/mdformat
formatter = { command = "mdformat", args = ["-"] }

# [[language]]
# name = "rust"
# config.check.command = "clippy"

# [[language]]
# name = "go"
# config = { "formatting.gofumpt" = true }

[[language]]
name = "yaml"
auto-format = true
# indent = { tab-width = 2, unit = "  " }
formatter = { command = "prettier", args = ["--parser", "yaml"] }
 
[[language]]
name = "lua"
auto-format = true
formatter = { command = "stylua", args = ["-"] }

[language-server.lua-language-server.config.Lua]
diagnostics = { globals = [ "vim", "hs" ] }
