---
# Configuration for zellij.

# In order to troubleshoot your configuration try using the following command:
# `zellij setup --check`
# It should show current config locations and features that are enabled.

keybinds:
    unbind: true
    normal:
        - action: [SwitchToMode: Tmux,]
          key: [Alt: 't',]
        - action: [Quit,]
          key: [Ctrl: 'q',]
        - action: [MoveFocus: Left,]
          key: [ Alt: 'h', Alt: Left]
        - action: [MoveFocus: Right,]
          key: [ Alt: 'l', Alt: Right ]
        - action: [MoveFocus: Down,]
          key: [ Alt: 'j', Alt: Down]
        - action: [MoveFocus: Up,]
          key: [ Alt: 'k', Alt: Up, ]
        - action: [GoToNextTab,]
          key: [ Alt: 'd']
        - action: [GoToPreviousTab,]
          key: [ Alt: 'a']
    scroll:
        - action: [SwitchToMode: Normal,]
          key: [Ctrl: 's', Char: ' ', Char: "\n", Esc]
        - action: [ScrollToBottom, SwitchToMode: Normal,]
          key: [Ctrl: 'c',]
        - action: [ScrollDown,]
          key: [Char: 'j', Down,]
        - action: [ScrollUp,]
          key: [Char: 'k', Up,]
        - action: [PageScrollDown,]
          key: [Ctrl: 'f', PageDown, Right, Char: 'l',]
        - action: [PageScrollUp,]
          key: [Ctrl: 'b', PageUp, Left, Char: 'h',]
        - action: [HalfPageScrollDown,]
          key: [Char: 'd',]
        - action: [HalfPageScrollUp,]
          key: [Char: 'u',]
        # - action: [Copy: ]
        #   key: [ Char: 'y']
    renametab:
        - action: [SwitchToMode: Normal,]
          key: [Char: "\n", Ctrl: 'c', Esc]
    tmux:
        - action: [SwitchToMode: Normal,]
          key: [Ctrl: 'o', Char: "\n", Char: ' ', Esc]
        - action: [SwitchToMode: Scroll,]
          key: [Ctrl: 's']
        - action: [SwitchToMode: Scroll,]
          key: [ Char: '[']
        - action: [Quit,]
          key: [Ctrl: 'q',]
        - action: [Write: [2,], SwitchToMode: Normal]
          key: [Ctrl: 'b']
        - action: [NewPane: Down, SwitchToMode: Normal,]
          key: [Char: '-',]
        - action: [NewPane: Right, SwitchToMode: Normal,]
          key: [Char: '\',]
        - action: [ToggleFocusFullscreen, SwitchToMode: Normal,]
          key: [Char: 'z',]
        - action: [NewTab: , SwitchToMode: Normal,]
          key: [ Char: 'c',]
        - action: [SwitchToMode: RenameTab, TabNameInput: [0],]
          key: [Char: ',']
        - action: [GoToPreviousTab,]
          key: [ Char: 'p']
        - action: [GoToNextTab,]
          key: [ Char: 'n']
        # - action: [MoveFocus: Left, SwitchToMode: Normal,]
        #   key: [ Left,]
        # - action: [MoveFocus: Right, SwitchToMode: Normal,]
        #   key: [ Right,]
        # - action: [MoveFocus: Down, SwitchToMode: Normal,]
        #   key: [ Down,]
        # - action: [MoveFocus: Up, SwitchToMode: Normal,]
        #   key: [ Up,]
        # - action: [MoveFocus: Left, SwitchToMode: Normal,]
        #   key: [ Char: 'h']
        # - action: [MoveFocus: Right, SwitchToMode: Normal,]
        #   key: [ Char: 'l']
        # - action: [MoveFocus: Down, SwitchToMode: Normal,]
        #   key: [ Char: 'j']
        # - action: [MoveFocus: Up, SwitchToMode: Normal,]
        #   key: [ Char: 'k']
        # - action: [NewPane: ,]
        #   key: [ Alt: 'n',]
        - action: [MoveFocusOrTab: Left,]
          key: [ Alt: 'h', Alt: Left]
        - action: [MoveFocusOrTab: Right,]
          key: [ Alt: 'l', Alt: Right]
        - action: [MoveFocus: Down,]
          key: [ Alt: 'j', Alt: Down]
        - action: [MoveFocus: Up,]
          key: [ Alt: 'k', Alt: Up]
        - action: [FocusNextPane,]
          key: [ Char: 'o']
        - action: [Resize: Down,]
          key: [ Char: 'J']
        - action: [Resize: Up,]
          key: [ Char: 'K']
        - action: [Resize: Left,]
          key: [ Char: 'H']
        - action: [Resize: Right,]
          key: [ Char: 'L']
        - action: [Detach,]
          key: [Char: 'd',]
        - action: [CloseFocus, SwitchToMode: Normal,]
          key: [Char: 'x',]
        - action: [CloseTab, SwitchToMode: Normal,]
          key: [ Char: 'X',]
        - action: [GoToTab: 1, SwitchToMode: Normal,]
          key: [ Char: '1',]
        - action: [GoToTab: 2, SwitchToMode: Normal,]
          key: [ Char: '2',]
        - action: [GoToTab: 3, SwitchToMode: Normal,]
          key: [ Char: '3',]
        - action: [GoToTab: 4, SwitchToMode: Normal,]
          key: [ Char: '4',]
        - action: [GoToTab: 5, SwitchToMode: Normal,]
          key: [ Char: '5',]
        - action: [GoToTab: 6, SwitchToMode: Normal,]
          key: [ Char: '6',]
        - action: [GoToTab: 7, SwitchToMode: Normal,]
          key: [ Char: '7',]
        - action: [GoToTab: 8, SwitchToMode: Normal,]
          key: [ Char: '8',]
        - action: [GoToTab: 9, SwitchToMode: Normal,]
          key: [ Char: '9',]

# plugins:
#     - path: tab-bar
#       tag: tab-bar
    # # - path: status-bar
    # #   tag: status-bar
    # - path: strider
    #   tag: strider

# Choose what to do when zellij receives SIGTERM, SIGINT, SIGQUIT or SIGHUP
# eg. when terminal window with an active zellij session is closed
# Options:
#   - detach (Default)
#   - quit
#on_force_close: quit

# Send a request for a simplified ui (without arrow fonts) to plugins
# Options:
#   - true
#   - false (Default)
#simplified_ui: true

# Choose the path to the default shell that zellij will use for opening new panes
# Default: $SHELL
default_shell: fish

# Toggle between having pane frames around the panes
# Options:
#   - true (default)
#   - false
pane_frames: false

# Choose the theme that is specified in the themes section.
# For some examples, see: https://github.com/zellij-org/zellij/tree/main/example/themes
# Default: default
#theme: default

# Choose the mode that zellij uses when starting up.
# Default: normal
#default_mode: locked

# Toggle enabling the mouse mode.
# On certain configurations, or terminals this could
# potentially interfere with copying text.
# Options:
#   - true (default)
#   - false
# mouse_mode: false

# Configure the scroll back buffer size
# This is the number of lines zellij stores for each pane in the scroll back
# buffer. Excess number of lines are discarded in a FIFO fashion.
# Valid values: positive integers
# Default value: 10000
#scroll_buffer_size: 10000

# Provide a command to execute when copying text. The text will be piped to
# the stdin of the program to perform the copy. This can be used with
# terminal emulators which do not support the OSC 52 ANSI control sequence
# that will be used by default if this option is not set.
# Examples:
#copy_command: "xclip -selection clipboard" # x11
#copy_command: "wl-copy"                    # wayland
copy_command: "pbcopy"                     # osx

# Choose the destination for copied text
# Allows using the primary selection buffer (on x11/wayland) instead of the system clipboard.
# Does not apply when using copy_command.
# Options:
#   - system (default)
#   - primary
copy_clipboard: system

# Enable or disable automatic copy (and clear) of selection when releasing mouse
copy_on_select: true

themes:
  tokyo-night:
    fg: [169,177,214] #A9B1D6
    bg: [26,27,38] #1A1B26
    black: [22,22,30] #16161e
    red: [249,51,87] #F9334D
    green: [65,166,181]  #41A6B5
    yellow: [224,175,104] #E0AF68
    blue: [122,162,247]  #7AA2F7
    magenta: [187,154,247] #BB9AF7
    cyan: [42,195,222] #2AC3DE
    white: [192,202,245] #C0CAF5
    orange: [255,158,100] #FF9E64
  tokyo-night-storm:
    fg: [169,177,214] #A9B1D6
    bg: [36,40,59] #24283B
    black: [56,62,90] #383E5A
    red: [249,51,87] #F9334D
    green: [158,206,106]  #9ECE6A
    yellow: [224,175,104] #E0AF68
    blue: [122,162,247]  #7AA2F7
    magenta: [187,154,247] #BB9AF7
    cyan: [42,195,222] #2AC3DE
    white: [192,202,245] #C0CAF5
    orange: [255,158,100] #FF9E64
  tokyo-night-light:
    fg: [52,59,88] #343B58
    bg: [213,214,219] #D5D6DB
    black: [15,15,20] #0F0F14
    red: [186,75,96] #BA4B60
    green: [72,94,48]  #485E30
    yellow: [143,94,21] #8F5E15
    blue: [52,84,138]  #34548A
    magenta: [90,74,120] #5A4A78
    cyan: [15,75,110] #0F4B6E
    white: [130,137,172] #8289AC
    orange: [150,80,39] #965027

theme: tokyo-night

ui:
  pane_frames:
    rounded_corners: true

